# Generated by Django 2.2.16 on 2022-02-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(help_text='Группа, к которой будет относиться пост',
                                  max_length=200,
                                  verbose_name='Название группы')),
                ('slug',
                 models.SlugField(help_text='Слаг, по которому можно найти группу',
                                  max_length=100,
                                  unique=True,
                                  verbose_name='Слаг')),
                ('description', models.TextField(
                    help_text='Тематика группы', verbose_name='Описание группы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={
                'ordering': (
                    '-created',
                ),
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                blank=True,
                help_text='Группа, к которой будет относиться пост',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='posts',
                to='posts.Group',
                verbose_name='Группа'),
        ),
    ]
